export const PARKS_LOADING = 'PARKS_LOADING';
export const PARKS_FAILED = 'PARKS_FAILED';
export const ADD_PARKS = 'ADD_PARKS';

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PARK_STATUS_LOADING = 'PARK_STATUS_LOADING';
export const PARK_STATUS_FAILED = 'PARK_STATUS_FAILED';
export const ADD_PARK_STATUS = 'ADD_PARK_STATUS';

export const PARK_INFO_LOADING = 'PARK_INFO_LOADING';
export const PARK_INFO_FAILED = 'PARK_INFO_FAILED';
export const ADD_PARK_INFO = 'ADD_PARK_INFO';

export const ADD_REPORT = "ADD_REPORT";