export const ALLPARKS_LOADING = 'ALLPARKS_LOADING';
export const ALLPARKS_FAILED = 'ALLPARKS_FAILED';
export const ADD_ALLPARKS = 'ADD_ALLPARKS';

export const BESTPARKS_LOADING = 'BESTPARKS_LOADING';
export const BESTPARKS_FAILED = 'BESTPARKS_FAILED';
export const ADD_BESTPARKS = 'ADD_BESTPARKS';

export const CHEAPPARKS_LOADING = 'CHEAPPARKS_LOADING';
export const CHEAPPARKS_FAILED = 'CHEAPPARKS_FAILED';
export const ADD_CHEAPPARKS = 'ADD_CHEAPPARKS';

export const NEARPARKS_LOADING = 'NEARPARKS_LOADING';
export const NEARPARKS_FAILED = 'NEARPARKS_FAILED';
export const ADD_NEARPARKS = 'ADD_NEARPARKS';

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PARK_STATUS_LOADING = 'PARK_STATUS_LOADING';
export const PARK_STATUS_FAILED = 'PARK_STATUS_FAILED';
export const ADD_PARK_STATUS = 'ADD_PARK_STATUS';

export const PARK_INFO_LOADING = 'PARK_INFO_LOADING';
export const PARK_INFO_FAILED = 'PARK_INFO_FAILED';
export const ADD_PARK_INFO = 'ADD_PARK_INFO';

export const ADD_REPORT = "ADD_REPORT";

export const USER_LOADING = 'USER_LOADING';
export const USER_FAILED = 'USER_FAILED';
export const ADD_USER = 'ADD_USER';